typography_spectrum: 0.2787077249959111
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8862866135314107
  lightness: 0.0035372567363083363
  saturation: 0.6554315541870892
  rhythmicContrast: 0.6007481603883207
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36308
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Joseba Attard
  email: info@josebaattard.com
  url: www.josebaattard.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/edd70718-7afd-4a21-acc9-4d8cec091e9b.jpg
name: Olabe
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/olabeproject'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b98d283-e645-4d71-874c-1264c0a3d792.png
title: Olabe - back to basics
content: []
description: >-
  A project to convert a 400 yr old Basque farmhouse into a cultural hub for
  conferences, retreats, camps, workshops and events. 
purpose:
  - type: external
    url: 'http://www.facebook.com/olabeproject'
    label: Follow the progress on Facebook
